# Generated by Django 4.2.1 on 2023-05-21 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='dislikes',
            field=models.IntegerField(default=0, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='like',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
