# Generated by Django 4.2.1 on 2023-05-22 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_category_dislikes_category_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='dislokes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comment',
            name='like',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='category',
            name='dislikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='category',
            name='like',
            field=models.IntegerField(default=0),
        ),
    ]
