# Generated by Django 4.2.1 on 2023-05-22 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_comment_dislokes_comment_like_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='dislokes',
            new_name='dislikes',
        ),
    ]
