# Generated by Django 4.2.1 on 2023-05-22 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_dislokes_comment_dislikes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='category',
            name='like',
        ),
    ]
